title: CULT VAULT
description: "Youth Culture, Trends, Movements "
footer_text: Copyright 2021 Your name
header_feature_image: ../uploads/photo-1572872137284-96787b3c57dd.webp
header_text: Cult Culture
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: ../uploads/cult-logo.png
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
