title: CULT VAULT
description: "Youth Culture, Trends, Movements "
footer_text: Copyright 2021 Your name
header_feature_image: ../uploads/istockphoto-1280200884-170667a.jpg
header_text: Cult Culture
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
