title: CULT VAULT
description: "Youth Culture, Trends, Movements "
footer_text: Copyright 2021 Your name
header_feature_image: ../uploads/cult-banner-final.png
header_text: ""
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: ../uploads/cult-logo.png
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
